--- #YAML:1.0
name:                Thread-Semaphore
version:             2.04
abstract:            Thread-safe semaphores
license:             perl
author:              
    - Jerry D. Hedden <jdhedden AT cpan DOT org>
generated_by:        ExtUtils::MakeMaker version 6.43_01
distribution_type:   module
requires:     
    Scalar::Util:                  1.1
    Test::More:                    0.5
    threads:                       0
    threads::shared:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
